# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20171209_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
