# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 23:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_scorecard_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorecard',
            name='date',
        ),
        migrations.AddField(
            model_name='scorecard',
            name='date_played',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
