# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20171209_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='noOfHoles',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
