# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_scorecard_total_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_par', models.PositiveIntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='hole',
            name='scorecard',
        ),
        migrations.AddField(
            model_name='round',
            name='holes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Hole'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Round'),
        ),
    ]
