# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20171214_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
