# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20171214_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
