# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20171216_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hole',
            name='round',
        ),
        migrations.AddField(
            model_name='hole',
            name='round',
            field=models.ManyToManyField(to='courses.Round'),
        ),
    ]
