# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rounds', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rounds.Round'),
        ),
        migrations.AddField(
            model_name='score',
            name='hole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Hole'),
        ),
        migrations.AddField(
            model_name='score',
            name='scorecard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Scorecard'),
        ),
        migrations.AddField(
            model_name='hole',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
