# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20171219_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_par',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
