# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 21:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rounds', '0001_initial'),
        ('courses', '0004_auto_20171219_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('hole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Hole')),
            ],
        ),
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_played', models.DateField(default=datetime.date.today, null=True)),
                ('noOfHoles', models.PositiveIntegerField(null=True)),
                ('total_score', models.PositiveIntegerField(null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('round', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rounds.Round')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='scorecard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecards.Scorecard'),
        ),
    ]
