# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecards', '0002_auto_20180117_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='scorecard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scorecards.Scorecard'),
        ),
    ]
